const CURRENT_SEARCH_DATA = 'CURRENT_SEARCH_DATA';
const SELECT_MENU_TYPE = 'SELECT_MENU_TYPE';
const CURRENT_MENU_PAGE = 'CURRENT_MENU_PAGE';

export {
    CURRENT_SEARCH_DATA,
    SELECT_MENU_TYPE,
    CURRENT_MENU_PAGE
};
