const CURRENT_SEARCH_DATA = 'CURRENT_SEARCH_DATA';
const CURRENT_PAGE = 'CURRENT_PAGE';
const PAGE_START_INDEX = 'PAGE_START_INDEX';
const PAGE_END_INDEX = 'PAGE_END_INDEX';
const SELECT_MENU_TYPE = 'SELECT_MENU_TYPE';
const CURRENT_SUB_MENU = 'CURRENT_SUB_MENU';
const SEARCH_KEY = 'SEARCH_KEY';
const SEARCH_STATUS = 'SEARCH_STATUS';

export {
    CURRENT_SEARCH_DATA,
    CURRENT_PAGE,
    PAGE_START_INDEX,
    PAGE_END_INDEX,
    SELECT_MENU_TYPE,
    CURRENT_SUB_MENU,
    SEARCH_KEY,
    SEARCH_STATUS
};
