const CURRENT_SEARCH_DATA = 'CURRENT_SEARCH_DATA';
const SELECT_MENU_TYPE = 'SELECT_MENU_TYPE';
const CURRENT_SUB_MENU = 'CURRENT_SUB_MENU';
const SEARCH_KEY = 'SEARCH_KEY';

export {
    CURRENT_SEARCH_DATA,
    SELECT_MENU_TYPE,
    CURRENT_SUB_MENU,
    SEARCH_KEY
};
