const SHOW_DETAIL_DIALOG = 'SHOW_DETAIL_DIALOG';
const HIDE_DETAIL_DIALOG = 'HIDE_DETAIL_DIALOG';
const DETAIL_ITEM = 'DETAIL_ITEM';

const UPDATE_DIALOG = 'UPDATE_DIALOG';

export {
    SHOW_DETAIL_DIALOG,
    HIDE_DETAIL_DIALOG,
    DETAIL_ITEM,
    UPDATE_DIALOG
};
