const GET_MENU_START = 'GET_MENU_START';
const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS';
const GET_MENU_FAILED = 'GET_MENU_FAILED';

const MENU_ITEM_CLICKED = 'MENU_ITEM_CLICKED';

export {
    GET_MENU_START,
    GET_MENU_SUCCESS,
    GET_MENU_FAILED,
    MENU_ITEM_CLICKED,
};
