const SHOW_DELETE_DIALOG = 'SHOW_DELETE_DIALOG';
const HIDE_DELETE_DIALOG = 'HIDE_DELETE_DIALOG';
const DELETE_ITEM = 'DELETE_ITEM';

const UPDATE_DIALOG = 'UPDATE_DIALOG';

export {
    SHOW_DELETE_DIALOG,
    HIDE_DELETE_DIALOG,
    DELETE_ITEM,
    UPDATE_DIALOG
};
