const GET_MACHINE_DATA_START = 'GET_MACHINE_DATA_START';
const GET_MACHINE_DATA_SUCCESS = 'GET_MACHINE_DATA_SUCCESS';
const GET_MACHINE_DATA_FAILED = 'GET_MACHINE_DATA_FAILED';

const EDIT_DATA_ITEM_START = 'EDIT_DATA_ITEM_START';
const EDIT_DATA_ITEM_SUCCESS = 'EDIT_DATA_ITEM_SUCCESS';
const EDIT_DATA_ITEM_FAILED = 'EDIT_DATA_ITEM_FAILED';

const MACHINE_DATA_ITEM_CLICKED = 'MACHINE_DATA_ITEM_CLICKED';
// const FORCE_UPDATE_PUBLIC_CHANNEL_LIST = 'FORCE_UPDATE_PUBLIC_CHANNEL_LIST';


export {
    GET_MACHINE_DATA_START,
    GET_MACHINE_DATA_SUCCESS,
    GET_MACHINE_DATA_FAILED,
    EDIT_DATA_ITEM_START,
    EDIT_DATA_ITEM_SUCCESS,
    EDIT_DATA_ITEM_FAILED,
    MACHINE_DATA_ITEM_CLICKED,
    // FORCE_UPDATE_PUBLIC_CHANNEL_LIST,
};
