const SHOW_ADD_DIALOG = 'SHOW_ADD_DIALOG';
const HIDE_ADD_DIALOG = 'HIDE_ADD_DIALOG';
const ADD_ITEM_START = 'ADD_ITEM_START';
const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
const ADD_ITEM_FAILED = 'ADD_ITEM_FAILED';

const UPDATE_DIALOG = 'UPDATE_DIALOG';

export {
    SHOW_ADD_DIALOG,
    HIDE_ADD_DIALOG,
    ADD_ITEM_START,
    ADD_ITEM_SUCCESS,
    ADD_ITEM_FAILED,
    UPDATE_DIALOG
};
