const SHOW_DELETE_DIALOG = 'SHOW_DELETE_DIALOG';
const HIDE_DELETE_DIALOG = 'HIDE_DELETE_DIALOG';
const DELETE_ITEM_START = 'DELETE_ITEM_START';
const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
const DELETE_ITEM_FAILED = 'DELETE_ITEM_FAILED';

const UPDATE_DIALOG = 'UPDATE_DIALOG';

export {
    SHOW_DELETE_DIALOG,
    HIDE_DELETE_DIALOG,
    DELETE_ITEM_START,
    DELETE_ITEM_SUCCESS,
    DELETE_ITEM_FAILED,
    UPDATE_DIALOG
};
